### ISSUE TITLE
关于获取地址UTXO的问题

### ISSUE THREAD

**Issue by juzi-code** [massnetorg/wallet-java-sdk#1]
addresses/utxos
这个函数只能获取节点已保存地址的UTXO吗？而不能获取任意地址的UTXO吗？

**Comment by Harry-Chen** [comment]
是的，全节点钱包只追踪它创建的地址的 UTXO。

**Comment by juzi-code** [comment]
我想做一个mass的钱包系统。
全节点钱包只追踪它创建的地址的 UTXO这个特性将导致我离线创建的地址，无法查询utxo，离线签名转账也将变得困难。
是不是我只能做在线的热钱包了。

**Comment by Harry-Chen** [comment]
在目前的设计下，您需要定期从全节点获得块，自行追踪 UTXO

**Comment by juzi-code** [comment]
明白您的意思了，谢谢。
